# Generated by Django 6.0.5 on 2026-05-13 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='literacyleaderboard',
            name='literacy_li_scope_abfe1c_idx',
        ),
        migrations.AddField(
            model_name='literacyleaderboard',
            name='books_read_score',
            field=models.IntegerField(default=0, help_text='10 pts per verified review'),
        ),
        migrations.AddField(
            model_name='literacyleaderboard',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='literacyleaderboard',
            name='quality_bonus_score',
            field=models.IntegerField(default=0, help_text='+5 pts if summary > 500 chars'),
        ),
        migrations.AddField(
            model_name='literacyleaderboard',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterUniqueTogether(
            name='literacyleaderboard',
            unique_together={('student', 'month', 'year')},
        ),
        migrations.AlterField(
            model_name='literacyleaderboard',
            name='consistency_score',
            field=models.IntegerField(default=0, help_text='5 pts per weekly streak, max 20 weeks'),
        ),
        migrations.AddIndex(
            model_name='literacyleaderboard',
            index=models.Index(fields=['month', 'year', '-total_score'], name='literacy_li_month_c745bc_idx'),
        ),
        migrations.RemoveField(
            model_name='literacyleaderboard',
            name='verified_reviews',
        ),
    ]
