# Generated by Django 6.0.5 on 2026-05-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literacy', '0002_remove_literacyleaderboard_literacy_li_scope_abfe1c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='literacyleaderboard',
            name='literacy_li_month_c745bc_idx',
        ),
        migrations.AlterUniqueTogether(
            name='literacyleaderboard',
            unique_together=set(),
        ),
    ]
