# Generated by Django 6.0.4 on 2026-05-15 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literacy', '0003_remove_literacyleaderboard_literacy_li_month_c745bc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='literacyleaderboard',
            unique_together={('student', 'month', 'year')},
        ),
        migrations.AddIndex(
            model_name='literacyleaderboard',
            index=models.Index(fields=['month', 'year', '-total_score'], name='literacy_li_month_c745bc_idx'),
        ),
    ]
