# Generated by Django 6.0.5 on 2026-05-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literacy', '0004_alter_literacyleaderboard_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='literacyleaderboard',
            options={'ordering': ['-total_score', 'first_activity_at', 'student__first_name']},
        ),
        migrations.AddField(
            model_name='literacyleaderboard',
            name='first_activity_at',
            field=models.DateTimeField(blank=True, help_text='Earliest verification in this period', null=True),
        ),
    ]
