# Generated by Django 6.0.5 on 2026-05-19 02:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literacy', '0005_alter_literacyleaderboard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='literacypost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
