# Generated by Django 6.0.4 on 2026-05-19 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literacy', '0006_alter_bookreview_created_at_and_more'),
        ('literacy', '0008_add_verification_fields'),
    ]

    operations = [
    ]
