# Generated by Django 6.0.5 on 2026-06-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literacy', '0009_merge_20260519_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='literacyleaderboard',
            name='book_rating_score',
            field=models.IntegerField(default=0, help_text='+2 pts per book rating & review submitted in catalog'),
        ),
    ]
