# Generated by Django 6.0.5 on 2026-06-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literacy', '0010_literacyleaderboard_book_rating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='literacyleaderboard',
            name='book_loans_count',
            field=models.IntegerField(default=0, help_text='Number of book loans in this period'),
        ),
        migrations.AddField(
            model_name='literacyleaderboard',
            name='book_loans_score',
            field=models.IntegerField(default=0, help_text='+2 pts per approved book loan'),
        ),
    ]
