# Generated by Django 6.0.4 on 2026-06-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literacy', '0011_commentreport'),
        ('literacy', '0011_literacyleaderboard_book_loans_count_and_more'),
    ]

    operations = [
    ]
