# Generated by Django 6.0.2 on 2026-03-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('menunggu_konfirmasi', 'Menunggu Konfirmasi'), ('siap_diambil', 'Siap Diambil'), ('sedang_dipinjam', 'Sedang Dipinjam'), ('menunggu_persetujuan_perpanjangan', 'Menunggu Persetujuan Perpanjangan'), ('terlambat', 'Terlambat'), ('dikembalikan', 'Dikembalikan'), ('ditolak', 'Ditolak')], default='menunggu_konfirmasi', max_length=40),
        ),
    ]
