# Generated by Django 6.0.4 on 2026-05-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_loan', '0004_add_selesai_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('menunggu_konfirmasi', 'Menunggu Konfirmasi'), ('siap_diambil', 'Siap Diambil'), ('sedang_dipinjam', 'Sedang Dipinjam'), ('menunggu_persetujuan_perpanjangan', 'Menunggu Persetujuan Perpanjangan'), ('terlambat', 'Terlambat'), ('dikembalikan', 'Dikembalikan'), ('ditolak', 'Ditolak'), ('dibatalkan', 'Dibatalkan')], default='menunggu_konfirmasi', max_length=40),
        ),
    ]
