# Generated by Django 5.1.3 on 2026-04-20 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('librarian', 'Librarian')], default='student', max_length=20)),
                ('nis', models.CharField(blank=True, help_text='Nomor Induk Siswa', max_length=20, null=True, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('L', 'Laki-laki (Male)'), ('P', 'Perempuan (Female)')], max_length=1, null=True)),
                ('kelas', models.CharField(blank=True, help_text='Kelas/Class', max_length=50, null=True)),
                ('is_active_student', models.BooleanField(default=True, help_text='Status aktif siswa. False jika sudah lulus atau tidak aktif.')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Waktu siswa dinonaktifkan (soft delete)', null=True)),
                ('deactivation_reason', models.CharField(blank=True, choices=[('graduated', 'Lulus Sekolah'), ('transferred', 'Pindah Sekolah'), ('other', 'Lainnya')], help_text='Alasan deactivasi', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
