# Generated by Django 6.0.4 on 2026-04-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='Waktu siswa dinonaktifkan (soft delete)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deactivation_reason',
            field=models.CharField(blank=True, choices=[('graduated', 'Lulus Sekolah'), ('transferred', 'Pindah Sekolah'), ('other', 'Lainnya')], help_text='Alasan deactivasi', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active_student',
            field=models.BooleanField(default=True, help_text='Status aktif siswa. False jika sudah lulus atau tidak aktif.'),
        ),
    ]
