# Generated by Django 6.0.5 on 2026-05-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Foto profil pengguna', null=True, upload_to='profile_pictures/'),
        ),
    ]