# Generated by Django 6.0.2 on 2026-03-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Usulan Buku', 'verbose_name_plural': 'Usulan Buku'},
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='catatan_petugas',
            field=models.TextField(blank=True, help_text='Catatan petugas saat menyetujui atau menolak usulan'),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='publisher',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='notification_seen',
            field=models.BooleanField(default=False, help_text='True setelah pengaju menutup pop-up notifikasi status'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='reason',
            field=models.TextField(help_text='Alasan pengajuan buku ini (maks. 500 karakter)'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20),
        ),
    ]
