# Generated by Django 6.0.2 on 2026-03-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_publish_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='damaged_copies',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='lost_copies',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
