# Generated by Django 6.0.2 on 2026-04-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_review_deleted_at_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
